add_newline = true

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration\
  $custom\
  $line_break\
  $jobs\
  $time\
  $character\
  """

command_timeout = 800

[shell]
disabled = false
style = "bold"
bash_indicator = "[bsh](#a593e0)"
zsh_indicator = "[zsh](#fff1b9)"
powershell_indicator = "[psh](#f7aa97)"
cmd_indicator = "[cmd](#a3daff)"

[character]
success_symbol = "[❯](bold #00ff00)"
error_symbol = "[✘](bold #ff4444)"
vicmd_symbol = "[❮](bold fg:79)"

[battery]
disabled = true

[directory]
truncate_to_repo = false
style = "bold fg:104"

[git_branch]
style = "fg:103"

[git_state]
style = "fg:104"

[git_status]
style = "fg:104"

