[settings]
experimental = true

[tools]
watchexec = 'latest'
python = "latest"
deno = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-update" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
go = "latest"
rust = "latest"
node = "23.1.0"
