[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[tools]
watchexec = 'latest'
python = "latest"
deno = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-update" = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
go = "latest"
node = "20"
"cargo:eza" = "latest"
rust = "latest"
