[settings]
experimental = true

[tools]
node = "latest"
go = ['1.21', '1.18']
watchexec = 'latest'
python = "latest"
deno = "latest"
bun = "latest"
cargo = "latest"
"cargo:eza" = "latest"
rust = "latest"
